server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:mem:taskflow
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
#  level:
#    root: INFO
#    com.taskflow: DEBUG
#    org.springframework.security: DEBUG

app:
  jwt-secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwt-expiration-milliseconds: 86400000
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173

#logging:
#  level:
#    root: INFO
#    com.taskflow: DEBUG
#    org.springframework.security: INFO
#    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/application.log
#    max-size: 10MB
#    max-history: 30

#mvc:
#  throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false
#
#error:
#  include-message: always
#  include-binding-errors: always
#  include-stacktrace: never
#  include-exception: false